force-app/main/default/objects/tc9_et__Timesheet__c/tc9_et__Timesheet__c.object-meta.xml
<CustomObject>
    <description>A master object that holds details of time worked, expenses and allowances. The Timesheet holds header information and groups Timesheet Entries, Expenses and Allowances so they can go through a submission/approval process</description>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Timesheet</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/tc9_et__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Approval_Status__c</fullName>
    <description>The Approval Status of the Timesheet</description>
    <inlineHelpText>The Approval Status of the Timesheet</inlineHelpText>
    <label>Approval Status (No Colour)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>tc9_et__Approval_Status_Picklists</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/tc9_et__Assignment__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Assignment that applies to the Timesheet</description>
    <inlineHelpText>Defines the Assignment that applies to the Timesheet</inlineHelpText>
    <label>Assignment</label>
    <referenceTo>tc9_pr__Assignment__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/tc9_et__End_Date__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__End_Date__c</fullName>
    <description>Indicates the End Date of the Timesheet</description>
    <inlineHelpText>Indicates the End Date of the Timesheet</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/tc9_et__Payee__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Payee that applies to the Timesheet</description>
    <inlineHelpText>Defines the Payee that applies to the Timesheet</inlineHelpText>
    <label>Payee</label>
    <referenceTo>tc9_pr__Payee__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/tc9_et__Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Total_Hours__c</fullName>
    <description>The total number of hours for the Timesheet</description>
    <inlineHelpText>The total number of hours for the Timesheet</inlineHelpText>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/tc9_et__Transaction_Creation_Stage__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Transaction_Creation_Stage__c</fullName>
    <description>The stage in the transaction creation process the Timesheet is in, updated by the application automatically. 
1 - Timesheet has not been approved 
2 - Timesheet Approved, ready to be processed 
3 - Timesheet has had Transactions created 
4 - The process to create Transactions failed - check Debug Log</description>
    <inlineHelpText>The stage in the transaction creation process the Timesheet is in 
1 - Timesheet has not been approved
2 - Timesheet Approved, ready to be processed
3 - Timesheet has had Transactions created
4 - The process to create Transactions failed - check Debug</inlineHelpText>
    <label>Transaction Creation Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>tc9_et__Generate_Transaction_Picklists</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/x2c9_Cross_Assignment_Details__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Cross_Assignment_Details__c</fullName>
    <description>Details related to the cross-assignment interpretation functionality.
This field will be automatically populated by the process.</description>
    <inlineHelpText>Details related to the cross-assignment interpretation functionality.
This field will be automatically populated by the process.</inlineHelpText>
    <label>Cross Assignment Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/x2c9_Cross_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Cross_Assignment_Status__c</fullName>
    <description>Current status of the cross-assignment interpretation process.</description>
    <inlineHelpText>Current status of the cross-assignment interpretation process.</inlineHelpText>
    <label>Cross Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Insert</fullName>
            </value>
            <value>
                <fullName>Pending Delete</fullName>
            </value>
            <value>
                <fullName>Insert Failed</fullName>
            </value>
            <value>
                <fullName>Delete Failed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/x2c9_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Start_Date__c</fullName>
    <formula>IF(tc9_et__Start_Date__c&lt;tc9_et__Assignment__r.tc9_pr__Assignment_Start_Date__c, tc9_et__Assignment__r.tc9_pr__Assignment_Start_Date__c, tc9_et__Start_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/tc9_et__Timesheet_Entry__c.object-meta.xml
<CustomObject>
    <description>A child object to the Timesheet that holds individual entry details of time worked and any related Project Codes and Leave Events.</description>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TSE-{0000000000}</displayFormat>
        <label>Timesheet Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/tc9_et__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Approval_Status__c</fullName>
    <description>The Approval Status of the Timesheet Entry</description>
    <formula>If( 
tc9_et__Approval_Flag__c, 
&quot;Approved&quot;, 
If( 
tc9_et__Rejection_Flag__c , 
&quot;Rejected&quot;, 
If( 
tc9_et__Submitted_Flag__c, 
&quot;Submitted&quot;,
&quot;New&quot;
) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Approval Status of the Timesheet Entry</inlineHelpText>
    <label>Approval Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/tc9_et__Assignment__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Assignment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Defines the Assignment that applies to the Timesheet Entry</description>
    <inlineHelpText>Defines the Assignment that applies to the Timesheet Entry</inlineHelpText>
    <label>Assignment</label>
    <referenceTo>tc9_pr__Assignment__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/tc9_et__End_Date__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__End_Date__c</fullName>
    <description>Identifies the End Date of the Timesheet Entry</description>
    <inlineHelpText>Identifies the End Date of the Timesheet Entry</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/tc9_et__Payee__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Payee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Defines the Payee that applies to the Timesheet Entry</description>
    <inlineHelpText>Defines the Payee that applies to the Timesheet Entry</inlineHelpText>
    <label>Payee</label>
    <referenceTo>tc9_pr__Payee__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/tc9_et__Project_Code__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Project_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Project Code that applies to the Timesheet Entry</description>
    <inlineHelpText>Defines the Project Code that applies to the Timesheet Entry</inlineHelpText>
    <label>Project Code</label>
    <referenceTo>tc9_pr__Project_Code__c</referenceTo>
    <relationshipLabel>Timesheet Entries (Project Code)</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/tc9_et__Timesheet__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Timesheet__c</fullName>
    <description>Defines the Timesheet that applies to the Timesheet Entry</description>
    <inlineHelpText>Defines the Timesheet that applies to the Timesheet Entry</inlineHelpText>
    <label>Timesheet</label>
    <referenceTo>tc9_et__Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/tc9_et__Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Total_Hours__c</fullName>
    <description>Defines the Total Hours for the Timesheet Entry as a number</description>
    <inlineHelpText>Defines the Total Hours for the Timesheet Entry as a number</inlineHelpText>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/x2c9_Cross_Assignment_Group_By_ID__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Cross_Assignment_Group_By_ID__c</fullName>
    <formula>tc9_et__Assignment__r.x2c9_Cross_Assignment_Group_By_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cross Assignment Group By ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/x2c9_Cross_Assignment_Timesheet_Entry__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Cross_Assignment_Timesheet_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cross Assignment Timesheet Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Assignment__c/tc9_pr__Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_pr__Assignment__c/fields/x2c9_Cross_Assignment_Group_By_ID__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Cross_Assignment_Group_By_ID__c</fullName>
    <label>Cross Assignment Group By ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Assignment__c/fields/x2c9_Cross_Assignment_Timesheet_Status__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Cross_Assignment_Timesheet_Status__c</fullName>
    <description>Defines which Timesheets will be included in the cross-assignment interpretation process.

Approved - Only Timesheets that meet the cross-assignment criteria wth an Approval Status of &apos;Approved&apos; will be processed for cross-assignment interpretation.

All - All Timesheets that meet the cross-assignment criteria will be processed for cross-assignment interpretation.</description>
    <inlineHelpText>Defines which Timesheets will be included in the cross-assignment interpretation process.

Approved - Only Timesheets that meet the cross-assignment criteria wth an Approval Status of &apos;Approved&apos; will be processed for cross-assignment interpretation.

All - All Timesheets that meet the cross-assignment criteria will be processed for cross-assignment interpretation.</inlineHelpText>
    <label>Cross Assignment Timesheet Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/tc9_pr__Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Area__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Area__c</fullName>
    <description>The class which generated this Debug Header.</description>
    <inlineHelpText>The class which generated this Debug Header.</inlineHelpText>
    <label>Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Record_Detail__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Record_Detail__c</fullName>
    <description>The record which created this Debug Log.</description>
    <inlineHelpText>The record which created this Debug Log.</inlineHelpText>
    <label>Record Detail</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Source__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Source__c</fullName>
    <description>The source process which generated this Debug Log.</description>
    <inlineHelpText>The source process which generated this Debug Log.</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/tc9_et__Approval_Status_Picklists.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>To be used for Approval Status based picklist fields</description>
    <masterLabel>Approval Status Picklists</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/tc9_et__Generate_Transaction_Picklists.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <default>true</default>
        <label>1</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <description>To be used for Generate Transaction picklist fields</description>
    <masterLabel>Generate Transaction Picklists</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/X2c9_CrossAssignmentInsertBatch.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public class X2c9_CrossAssignmentInsertBatch implements Database.Batchable<sObject>, Schedulable {

    public static final String LOG_AREA = 'X2c9_CrossAssignmentInsertBatch';
    public static final String LOG_DESCRIPTION = 'One or more errors from X2c9_CrossAssignmentInsertBatch. See Debug Lines for details.';
    public static final String LOG_PROCESS_NAME = 'Insert dummy Cross-Assignment Timesheet Entries and Pay Transactions before Timesheet interpretation';
    
    private List<Id> timesheetIds;

    public void execute(SchedulableContext sc) {
        insertCrossAssignment(null);
    }

    @InvocableMethod(label = 'Cross assignment insertion')
    public static void insertCrossAssignment(List<List<id>> timesheetIds) {
        List<Id> tsIds = new List<Id>();
        if(timesheetIds != null) {
            for (List<Id> request : timesheetIds) {
                tsIds.addAll(request);
            }
        }

        List<AsyncApexJob> jobs = [SELECT Id, ApexClassId, Status 
                                   FROM AsyncApexJob 
                                   WHERE ApexClassId IN (SELECT Id FROM ApexClass WHERE Name = 'X2c9_CrossAssignmentInsertBatch')
                                   AND Status NOT IN ('Aborted', 'Completed', 'Failed')
                                   AND JobType = 'BatchApex'];
        if (jobs.isEmpty()) {
            X2c9_CrossAssignmentInsertBatch batch = new X2c9_CrossAssignmentInsertBatch();
            batch.timesheetIds = tsIds;

            Database.executeBatch(batch, 1);
        }
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        updateValidationSetting(true);
        String query = ' SELECT Id, tc9_et__End_Date__c, ' + 
                       ' tc9_et__Assignment__r.x2c9_Cross_Assignment_Group_By_ID__c, tc9_et__Assignment__r.x2c9_Cross_Assignment_Timesheet_Status__c, x2c9_Start_Date__c, tc9_et__Payee__c, ' + 
                       '  (SELECT Id, tc9_et__Timesheet__c FROM tc9_et__Timesheet_Entries__r ' + 
                       '   WHERE x2c9_Cross_Assignment_Timesheet_Entry__c = TRUE) ' + 
                       ' FROM tc9_et__Timesheet__c ' +
                       ' WHERE x2c9_Cross_Assignment_Status__c = \'Pending Insert\' ';

        if (timesheetIds != null && !timesheetIds.isEmpty()) {
            query += ' AND Id IN :timesheetIds';
        }

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<tc9_et__Timesheet__c> timesheets) {
        System.debug('[EXECUTE] X2c9_CrossAssignmentInsertBatch.execute timesheets=' + timesheets);
        List<tc9_et__Timesheet_Entry__c> delEntries = new List<tc9_et__Timesheet_Entry__c>();

        Set<String> crossAssignmentGrpSet = new Set<String>();
        for (tc9_et__Timesheet__c ts : timesheets) {
            crossAssignmentGrpSet.add(ts.tc9_et__Assignment__r.x2c9_Cross_Assignment_Group_By_ID__c);

            if (ts.tc9_et__Timesheet_Entries__r != null && !ts.tc9_et__Timesheet_Entries__r.isEmpty()) {
                delEntries.addAll(ts.tc9_et__Timesheet_Entries__r);
            }
        }

        System.debug('[INFO] X2c9_CrossAssignmentInsertBatch.execute delEntries size=' + delEntries.size() + ' delEntries=' + delEntries);
        
        Map<String, List<tc9_et__Timesheet_Entry__c>> nonCrossAssignmentTseMap = getNonCrossAssignmentTseMap(crossAssignmentGrpSet);
        System.debug('[INFO] X2c9_CrossAssignmentInsertBatch.execute nonCrossAssignmentTseMap=' + nonCrossAssignmentTseMap);

        List<tc9_et__Timesheet_Entry__c> newEntries = new List<tc9_et__Timesheet_Entry__c>();
        for (tc9_et__Timesheet__c ts : timesheets) {
            List<tc9_et__Timesheet_Entry__c> nonCrossAssignmentTSEs = nonCrossAssignmentTseMap.get(ts.tc9_et__Assignment__r.x2c9_Cross_Assignment_Group_By_ID__c);
            Set<String> relatedTimesheetNames = new Set<String>();
        
            System.debug('X2c9_CrossAssignmentInsertBatch.execute nonCrossAssignmentTSEs=' + nonCrossAssignmentTSEs);
        
            if (nonCrossAssignmentTSEs == null || nonCrossAssignmentTSEs.isEmpty()) {
                updateTimesheetStatusAndDetails(ts, relatedTimesheetNames, false);
                continue; // Use continue to skip to the next iteration
            }

            processCrossAssignmentTSEs(ts, nonCrossAssignmentTSEs, newEntries, relatedTimesheetNames);
            updateTimesheetStatusAndDetails(ts, relatedTimesheetNames, true);
        }

        System.debug('[INFO] X2c9_CrossAssignmentInsertBatch.execute newEntries=' + newEntries);
        System.debug('[INFO] X2c9_CrossAssignmentInsertBatch.execute newEntries.size()=' + newEntries.size());

        Set<Id> failedInsLineTimesheetIdset = new Set<Id>();
        List<tc9_pr__Debug_Log__c> logs = new List<tc9_pr__Debug_Log__c>();


        X2c9_CrossAssignmentBatchHelper.insertTimesheetEntries(newEntries, logs, failedInsLineTimesheetIdset);
        X2c9_CrossAssignmentBatchHelper.deleteTimesheetEntries(delEntries, logs);


        System.debug('failedInsLineTimesheetIdset=' + failedInsLineTimesheetIdset);

        if(!failedInsLineTimesheetIdset.isEmpty()) {
            for(tc9_et__Timesheet__c ts : timesheets)  {
                if(failedInsLineTimesheetIdset.contains(ts.Id)) {
                    ts.x2c9_Cross_Assignment_Status__c = 'Insert Failed';
                    ts.x2c9_Cross_Assignment_Details__c = 'Cross-Assignment Insert Failed, Check Debug Logs for Error - ' + System.now();
                }
            }

            //delete all inserted TSEs if there is any failed insertion
            deleteErrorTSE(failedInsLineTimesheetIdset);
        }

        X2c9_CrossAssignmentBatchHelper.insertLogs(logs, LOG_AREA, LOG_DESCRIPTION, LOG_PROCESS_NAME);
        update timesheets;
    }

    public void finish(Database.BatchableContext bc) {
        updateValidationSetting(false);
    }

    private static Map<String, List<tc9_et__Timesheet_Entry__c>> getNonCrossAssignmentTseMap(Set<String> crossAssignmentGrpSet) {
        Map<String, List<tc9_et__Timesheet_Entry__c>> nonCrossAssignmentTseMap = new Map<String,List<tc9_et__Timesheet_Entry__c>>();
        String queryTSEStr = ' SELECT ' + getFields('tc9_et__Timesheet_Entry__c') +
                             ' , tc9_et__Timesheet__r.Name ' + 
                             ' FROM tc9_et__Timesheet_Entry__c WHERE x2c9_Cross_Assignment_Timesheet_Entry__c = FALSE ' + 
                             ' AND tc9_et__Total_Hours__c > 0 ' +
                             ' AND x2c9_Cross_Assignment_Group_By_ID__c IN :crossAssignmentGrpSet ';

        List<tc9_et__Timesheet_Entry__c> tses = Database.query(queryTSEStr);
        for(tc9_et__Timesheet_Entry__c tse : tses) {
            if(!nonCrossAssignmentTseMap.containsKey(tse.x2c9_Cross_Assignment_Group_By_ID__c)) {
                nonCrossAssignmentTseMap.put(tse.x2c9_Cross_Assignment_Group_By_ID__c, new List<tc9_et__Timesheet_Entry__c>{tse});
                
            } else {
                nonCrossAssignmentTseMap.get(tse.x2c9_Cross_Assignment_Group_By_ID__c).add(tse);
            }
        }

        return nonCrossAssignmentTseMap;
    }

    @SuppressWarnings('PMD.ExcessiveParameterList')
    private void processCrossAssignmentTSEs(tc9_et__Timesheet__c ts, List<tc9_et__Timesheet_Entry__c> nonCrossAssignmentTSEs, List<tc9_et__Timesheet_Entry__c> newEntries, Set<String> relatedTimesheetNames) {
        String status = ts.tc9_et__Assignment__r.x2c9_Cross_Assignment_Timesheet_Status__c;    
        for(tc9_et__Timesheet_Entry__c tse : nonCrossAssignmentTSEs) {
            Boolean isApprovedAndMatches = (status == 'Approved' && tse.tc9_et__Approval_Status__c == status);
            Boolean isNotApproved = (status != 'Approved');

            if ((isApprovedAndMatches || isNotApproved) && validateTSE(ts, tse)) {
                tc9_et__Timesheet_Entry__c newEntry = cloneTSE(tse, ts);
                newEntries.add(newEntry);
                relatedTimesheetNames.add(tse.tc9_et__Timesheet__r.Name);
            }
        }
    }

    private void updateTimesheetStatusAndDetails(tc9_et__Timesheet__c timesheet, Set<String> relatedNames, Boolean foundEntries) {
        timesheet.tc9_et__Transaction_Creation_Stage__c = '2';
        timesheet.x2c9_Cross_Assignment_Status__c = 'Pending Delete';
    
        if (foundEntries) {
            String detail = 'Timesheets Included in Cross-Assignment Interpretation:' + String.join(new List<String>(relatedNames), ',') + ' - ' + System.now();
            timesheet.x2c9_Cross_Assignment_Details__c = detail.left(255);
        } else {
            timesheet.x2c9_Cross_Assignment_Details__c = 'No Cross-Assignment Timesheets Found';
        }
    }

    @Testvisible
    private static void deleteErrorTSE(Set<Id> failedInsLineTimesheetIdset) {
        List<tc9_et__Timesheet_Entry__c> delTSEforErrorTS = new List<tc9_et__Timesheet_Entry__c>();
        List<tc9_et__Timesheet__c> errorTSs = [SELECT Id,tc9_et__End_Date__c,
                                                tc9_et__Assignment__r.x2c9_Cross_Assignment_Group_By_ID__c, tc9_et__Assignment__r.x2c9_Cross_Assignment_Timesheet_Status__c, x2c9_Start_Date__c, tc9_et__Payee__c, 
                                                    (SELECT Id, tc9_et__Timesheet__c 
                                                    FROM tc9_et__Timesheet_Entries__r 
                                                    WHERE x2c9_Cross_Assignment_Timesheet_Entry__c = TRUE) 
                                                FROM tc9_et__Timesheet__c
                                                WHERE Id IN :failedInsLineTimesheetIdset];
        
        for (tc9_et__Timesheet__c ts : errorTSs) {
            if (ts.tc9_et__Timesheet_Entries__r != null && !ts.tc9_et__Timesheet_Entries__r.isEmpty()) {
                delTSEforErrorTS.addAll(ts.tc9_et__Timesheet_Entries__r);
            }
        }

        Database.delete(delTSEforErrorTS, false);
    }

    public static tc9_pr__Debug_Log__c buildDebugLog(String recordId, String objectName, String error) {
        tc9_pr__Debug_Log__c log = new tc9_pr__Debug_Log__c();
        log.tc9_pr__Area__c = 'X2c9_CrossAssignmentInsertBatch';
        log.tc9_pr__Record_Detail__c = '<a href="/' + recordId + '" target="_blank">' + recordId + '</a>';
        log.tc9_pr__Source__c = 'Insert dummy Cross-Assignment ' + objectName + ' and Pay Transactions before Timesheet interpretation';
        log.tc9_pr__Record_Type__c = recordId;
        log.tc9_pr__Description__c = error?.left(10000);
        return log;
    }

    private static String getFields(String objectAPI){
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get(objectAPI).getDescribe().fields.getMap();
    
        return String.join(new List<String>(fieldMap.keySet()), ', ');
    }

    private static void updateValidationSetting(Boolean ovTSE) {
        tc9_pr__Override_TC9P_Validation__c setting = tc9_pr__Override_TC9P_Validation__c.getOrgDefaults();
        setting.tc9_et__OV_Timesheet_Entry__c = ovTSE;
        setting.tc9_et__OV_Timesheet__c = ovTSE;
        update setting;
    }

    private static tc9_et__Timesheet_Entry__c cloneTSE(tc9_et__Timesheet_Entry__c tse, tc9_et__Timesheet__c ts) {
        tc9_et__Timesheet_Entry__c newEntry = tse.clone(false, true, false, false);
        newEntry.tc9_et__Assignment__c = ts.tc9_et__Assignment__c;
        newEntry.tc9_et__Approval_Flag__c = true;
        newEntry.tc9_et__Submitted_Flag__c = true;
        newEntry.tc9_et__Timesheet__c = ts.Id;
        newEntry.x2c9_Cross_Assignment_Timesheet_Entry__c = true;
        newEntry.tc9_et__Date_Pay_Transaction_Generated__c = null;
        newEntry.tc9_et__Project_Code__c = null;
        newEntry.tc9_et__Timesheet_Activity__c = null;

        return newEntry;
    }

    //boolean validateTSE method
    private static Boolean validateTSE(tc9_et__Timesheet__c ts, tc9_et__Timesheet_Entry__c tse) {
        if(tse.tc9_et__Assignment__c != ts.tc9_et__Assignment__c && 
            tse.tc9_et__Start_Date__c <= ts.tc9_et__End_Date__c && 
            tse.tc9_et__Start_Date__c >= ts.x2c9_Start_Date__c) {
            return true;

        } else {
            return false;
        }
    }
}