force-app/main/default/objects/tc9_et__Timesheet__c/tc9_et__Timesheet__c.object-meta.xml
<CustomObject>
    <description>A master object that holds details of time worked, expenses and allowances. The Timesheet holds header information and groups Timesheet Entries, Expenses and Allowances so they can go through a submission/approval process</description>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Timesheet</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/tc9_et__Timesheet_Entry__c.object-meta.xml
<CustomObject>
    <description>A child object to the Timesheet that holds individual entry details of time worked and any related Project Codes and Leave Events.</description>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TSE-{0000000000}</displayFormat>
        <label>Timesheet Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/tc9_et__Timesheet__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Timesheet__c</fullName>
    <description>Defines the Timesheet that applies to the Timesheet Entry</description>
    <inlineHelpText>Defines the Timesheet that applies to the Timesheet Entry</inlineHelpText>
    <label>Timesheet</label>
    <referenceTo>tc9_et__Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Header__c/tc9_pr__Debug_Header__c.object-meta.xml
<CustomObject>
    <label>Debug Header</label>
    <nameField>
        <displayFormat>Debug Header - {000000}</displayFormat>
        <label>Debug Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_pr__Debug_Header__c/fields/tc9_pr__Area__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Area__c</fullName>
    <description>The class which generated this Debug Header.</description>
    <inlineHelpText>The class which generated this Debug Header.</inlineHelpText>
    <label>Area</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Header__c/fields/tc9_pr__Description__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Description__c</fullName>
    <description>The description of this Debug Header.</description>
    <inlineHelpText>The description of this Debug Header.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Header__c/fields/tc9_pr__Process_Name__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Process_Name__c</fullName>
    <description>The process name which generated this Debug Header.</description>
    <inlineHelpText>The process name which generated this Debug Header.</inlineHelpText>
    <label>Process Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Header__c/fields/tc9_pr__Source__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Source__c</fullName>
    <description>The source process which generated this Debug Header.</description>
    <inlineHelpText>The source process which generated this Debug Header.</inlineHelpText>
    <label>Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/tc9_pr__Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Area__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Area__c</fullName>
    <description>The class which generated this Debug Header.</description>
    <inlineHelpText>The class which generated this Debug Header.</inlineHelpText>
    <label>Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Debug_Header__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Debug_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related Debug Header.</description>
    <inlineHelpText>The related Debug Header.</inlineHelpText>
    <label>Debug Header</label>
    <referenceTo>tc9_pr__Debug_Header__c</referenceTo>
    <relationshipLabel>Debug Logs</relationshipLabel>
    <relationshipName>Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Description__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Description__c</fullName>
    <description>The description of this Debug Log.</description>
    <inlineHelpText>The description of this Debug Log.</inlineHelpText>
    <label>Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Record_Detail__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Record_Detail__c</fullName>
    <description>The record which created this Debug Log.</description>
    <inlineHelpText>The record which created this Debug Log.</inlineHelpText>
    <label>Record Detail</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Record_Type__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Record_Type__c</fullName>
    <description>Details of the record which created this Debug Log.</description>
    <inlineHelpText>Details of the record which created this Debug Log.</inlineHelpText>
    <label>Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Source__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Source__c</fullName>
    <description>The source process which generated this Debug Log.</description>
    <inlineHelpText>The source process which generated this Debug Log.</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/X2c9_CrossAssignmentBatchHelper.cls
public with sharing class X2c9_CrossAssignmentBatchHelper {
    
    @SuppressWarnings('PMD.ExcessiveParameterList')
    public static void insertLogs(List<tc9_pr__Debug_Log__c> logs, String area, String description, String processName) {
        if(!logs.isEmpty()) {
            tc9_pr__Debug_Header__c header = buildDebugHeader(area, description, processName);
            insert header; // NOPMD

            for(tc9_pr__Debug_Log__c log : logs) {
                log.tc9_pr__Debug_Header__c = header.Id;
            }
            insert logs; // NOPMD
        }
    }

    @SuppressWarnings('PMD.ExcessiveParameterList')
    public static void insertTimesheetEntries(List<tc9_et__Timesheet_Entry__c> newEntries, List<tc9_pr__Debug_Log__c> logs, Set<Id> failedInsLineTimesheetIdset) {
        if(!newEntries.isEmpty()) {
            Database.SaveResult[] insertResults = Database.insert(newEntries, false);
            for (Integer i = 0; i < insertResults.size(); i++) {
                if (!insertResults[i].isSuccess()) {
                    logs.add(buildCrossAssignmentInsertDebugLog(newEntries[i].Id, 'Timesheet Entries', JSON.serialize(insertResults[i].getErrors())));
                    failedInsLineTimesheetIdset.add(newEntries[i].tc9_et__Timesheet__c);
                } 
            }
        }
    }

    public static void deleteTimesheetEntries(List<tc9_et__Timesheet_Entry__c> delEntries, List<tc9_pr__Debug_Log__c> logs) {
        if(!delEntries.isEmpty()) {
            Database.DeleteResult[] delResults = Database.delete(delEntries, false);
            for (Integer i = 0; i < delResults.size(); i++) {
                if (!delResults[i].isSuccess()) {
                    logs.add(buildCrossAssignmentInsertDebugLog(delEntries[i].Id, 'Timesheet Entries', JSON.serialize(delResults[i].getErrors())));
                } 
            }
        }
    }
    
    public static tc9_pr__Debug_Header__c buildDebugHeader(String area, String description, String processName) {
        tc9_pr__Debug_Header__c header = new tc9_pr__Debug_Header__c();
        header.tc9_pr__Area__c = area;
        header.tc9_pr__Description__c = description;
        header.tc9_pr__Process_Name__c = processName;
        return header;
    }

    public static tc9_pr__Debug_Log__c buildCrossAssignmentInsertDebugLog(String recordId, String objectName, String error) {
        tc9_pr__Debug_Log__c log = new tc9_pr__Debug_Log__c();
        log.tc9_pr__Area__c = 'X2c9_CrossAssignmentInsertBatch';
        log.tc9_pr__Record_Detail__c = '<a href="/' + recordId + '" target="_blank">' + recordId + '</a>';
        log.tc9_pr__Source__c = 'Insert dummy Cross-Assignment ' + objectName + ' and Pay Transactions before Timesheet interpretation';
        log.tc9_pr__Record_Type__c = recordId;
        log.tc9_pr__Description__c = error?.left(10000);
        return log;
    }
}