force-app/main/default/objects/tc9_et__Invoice_Item__c/tc9_et__Invoice_Item__c.object-meta.xml
<CustomObject>
    <description>A child object to the Invoice that holds individual Quantity, Invoice Rate and Invoice Description details of the items being invoiced and related Project Codes and Purchase Order Numbers.</description>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>INVITM-{0000000000}</displayFormat>
        <label>Invoice Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_et__Invoice_Item__c/fields/tc9_et__Timesheet_Entry__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Timesheet_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Timesheet Entry that applies to the Invoice Item (if applicable)</description>
    <inlineHelpText>Defines the Timesheet Entry that applies to the Invoice Item (if applicable)</inlineHelpText>
    <label>Timesheet Entry</label>
    <referenceTo>tc9_et__Timesheet_Entry__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/tc9_et__Timesheet__c.object-meta.xml
<CustomObject>
    <description>A master object that holds details of time worked, expenses and allowances. The Timesheet holds header information and groups Timesheet Entries, Expenses and Allowances so they can go through a submission/approval process</description>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Timesheet</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/tc9_et__Transaction_Creation_Stage__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Transaction_Creation_Stage__c</fullName>
    <description>The stage in the transaction creation process the Timesheet is in, updated by the application automatically. 
1 - Timesheet has not been approved 
2 - Timesheet Approved, ready to be processed 
3 - Timesheet has had Transactions created 
4 - The process to create Transactions failed - check Debug Log</description>
    <inlineHelpText>The stage in the transaction creation process the Timesheet is in 
1 - Timesheet has not been approved
2 - Timesheet Approved, ready to be processed
3 - Timesheet has had Transactions created
4 - The process to create Transactions failed - check Debug</inlineHelpText>
    <label>Transaction Creation Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>tc9_et__Generate_Transaction_Picklists</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/x2c9_Cross_Assignment_Details__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Cross_Assignment_Details__c</fullName>
    <description>Details related to the cross-assignment interpretation functionality.
This field will be automatically populated by the process.</description>
    <inlineHelpText>Details related to the cross-assignment interpretation functionality.
This field will be automatically populated by the process.</inlineHelpText>
    <label>Cross Assignment Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet__c/fields/x2c9_Cross_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Cross_Assignment_Status__c</fullName>
    <description>Current status of the cross-assignment interpretation process.</description>
    <inlineHelpText>Current status of the cross-assignment interpretation process.</inlineHelpText>
    <label>Cross Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Insert</fullName>
            </value>
            <value>
                <fullName>Pending Delete</fullName>
            </value>
            <value>
                <fullName>Insert Failed</fullName>
            </value>
            <value>
                <fullName>Delete Failed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/tc9_et__Timesheet_Entry__c.object-meta.xml
<CustomObject>
    <description>A child object to the Timesheet that holds individual entry details of time worked and any related Project Codes and Leave Events.</description>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TSE-{0000000000}</displayFormat>
        <label>Timesheet Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/tc9_et__Timesheet__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Timesheet__c</fullName>
    <description>Defines the Timesheet that applies to the Timesheet Entry</description>
    <inlineHelpText>Defines the Timesheet that applies to the Timesheet Entry</inlineHelpText>
    <label>Timesheet</label>
    <referenceTo>tc9_et__Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/tc9_et__Timesheet_Entry__c/fields/x2c9_Cross_Assignment_Timesheet_Entry__c.field-meta.xml
<CustomField>
    <fullName>x2c9_Cross_Assignment_Timesheet_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cross Assignment Timesheet Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Header__c/tc9_pr__Debug_Header__c.object-meta.xml
<CustomObject>
    <label>Debug Header</label>
    <nameField>
        <displayFormat>Debug Header - {000000}</displayFormat>
        <label>Debug Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_pr__Debug_Header__c/fields/tc9_pr__Area__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Area__c</fullName>
    <description>The class which generated this Debug Header.</description>
    <inlineHelpText>The class which generated this Debug Header.</inlineHelpText>
    <label>Area</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Header__c/fields/tc9_pr__Description__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Description__c</fullName>
    <description>The description of this Debug Header.</description>
    <inlineHelpText>The description of this Debug Header.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Header__c/fields/tc9_pr__Process_Name__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Process_Name__c</fullName>
    <description>The process name which generated this Debug Header.</description>
    <inlineHelpText>The process name which generated this Debug Header.</inlineHelpText>
    <label>Process Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Header__c/fields/tc9_pr__Source__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Source__c</fullName>
    <description>The source process which generated this Debug Header.</description>
    <inlineHelpText>The source process which generated this Debug Header.</inlineHelpText>
    <label>Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/tc9_pr__Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Area__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Area__c</fullName>
    <description>The class which generated this Debug Header.</description>
    <inlineHelpText>The class which generated this Debug Header.</inlineHelpText>
    <label>Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Debug_Header__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Debug_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related Debug Header.</description>
    <inlineHelpText>The related Debug Header.</inlineHelpText>
    <label>Debug Header</label>
    <referenceTo>tc9_pr__Debug_Header__c</referenceTo>
    <relationshipLabel>Debug Logs</relationshipLabel>
    <relationshipName>Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Description__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Description__c</fullName>
    <description>The description of this Debug Log.</description>
    <inlineHelpText>The description of this Debug Log.</inlineHelpText>
    <label>Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Debug_Log__c/fields/tc9_pr__Record_Detail__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Record_Detail__c</fullName>
    <description>The record which created this Debug Log.</description>
    <inlineHelpText>The record which created this Debug Log.</inlineHelpText>
    <label>Record Detail</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Pay_Transaction__c/tc9_pr__Pay_Transaction__c.object-meta.xml
<CustomObject>
    <label>Pay Transaction</label>
    <nameField>
        <label>Pay Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pay Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/tc9_pr__Pay_Transaction__c/fields/tc9_et__Invoice_Item__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Invoice_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Invoice Item that applies to the Pay Transaction</description>
    <inlineHelpText>Defines the Invoice Item that applies to the Pay Transaction</inlineHelpText>
    <label>Invoice Item</label>
    <referenceTo>tc9_et__Invoice_Item__c</referenceTo>
    <relationshipLabel>Pay Transactions</relationshipLabel>
    <relationshipName>Pay_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Pay_Transaction__c/fields/tc9_et__Timesheet__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Timesheet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Defines the Timesheet that applies to the Pay Transaction (if applicable)</description>
    <inlineHelpText>Defines the Timesheet that applies to the Pay Transaction (if applicable)</inlineHelpText>
    <label>Timesheet</label>
    <referenceTo>tc9_et__Timesheet__c</referenceTo>
    <relationshipLabel>Pay Transactions</relationshipLabel>
    <relationshipName>Pay_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Pay_Transaction__c/fields/tc9_et__Timesheet_Entry__c.field-meta.xml
<CustomField>
    <fullName>tc9_et__Timesheet_Entry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Defines the Timesheet Entry that applies to the Pay Transaction (if applicable)</description>
    <inlineHelpText>Defines the Timesheet Entry that applies to the Pay Transaction (if applicable)</inlineHelpText>
    <label>Timesheet Entry</label>
    <referenceTo>tc9_et__Timesheet_Entry__c</referenceTo>
    <relationshipLabel>Pay Transactions</relationshipLabel>
    <relationshipName>Pay_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Pay_Transaction__c/fields/tc9_pr__Description__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Description__c</fullName>
    <description>A text based description of this Pay Transaction record.</description>
    <inlineHelpText>A text based description of this Pay Transaction record.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Pay_Transaction__c/fields/tc9_pr__Pay_Batch__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Pay_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The pay batch this pay transaction has been included in</description>
    <inlineHelpText>The pay batch this pay transaction has been included in</inlineHelpText>
    <label>Pay Batch</label>
    <referenceTo>tc9_pr__Pay_Batch__c</referenceTo>
    <relationshipLabel>Pay Transactions</relationshipLabel>
    <relationshipName>Pay_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Pay_Transaction__c/fields/tc9_pr__Pay_Transaction__c.field-meta.xml
<CustomField>
    <fullName>tc9_pr__Pay_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pay Transaction</label>
    <referenceTo>tc9_pr__Pay_Transaction__c</referenceTo>
    <relationshipLabel>Pay Transactions</relationshipLabel>
    <relationshipName>Pay_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Pay_Transaction__c/fields/tc9_util__Original_Pay_Transaction__c.field-meta.xml
<CustomField>
    <fullName>tc9_util__Original_Pay_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Pay Transaction</label>
    <referenceTo>tc9_pr__Pay_Transaction__c</referenceTo>
    <relationshipLabel>Pay Transactions (Original Pay Transaction)</relationshipLabel>
    <relationshipName>Pay_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/tc9_pr__Pay_Transaction__c/fields/tc9_util__Reversed_From_Timesheet__c.field-meta.xml
<CustomField>
    <fullName>tc9_util__Reversed_From_Timesheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reversed From Timesheet</label>
    <referenceTo>tc9_et__Timesheet__c</referenceTo>
    <relationshipLabel>Pay Transactions (Reversed From Timesheet)</relationshipLabel>
    <relationshipName>Pay_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/tc9_et__Generate_Transaction_Picklists.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <default>true</default>
        <label>1</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <description>To be used for Generate Transaction picklist fields</description>
    <masterLabel>Generate Transaction Picklists</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/X2c9_CrossAssignmentDeleteBatch.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public class X2c9_CrossAssignmentDeleteBatch  implements Database.Batchable<sObject>, Schedulable {

    private List<Id> timesheetIds;

    public void execute(SchedulableContext sc) {
        deleteCrossAssignment(null);
    }

    @InvocableMethod(label = 'Cross assignment deletion')
    public static void deleteCrossAssignment(List<List<Id>> timesheetIds) {
        List<Id> tsIds = new List<Id>();
        if(timesheetIds != null && !timesheetIds.isEmpty() && timesheetIds[0] != null) {
            for (List<Id> request : timesheetIds) {
                tsIds.addAll(request);
            }
        }

        List<AsyncApexJob> jobs = [SELECT Id, ApexClassId, Status 
                                   FROM AsyncApexJob 
                                   WHERE ApexClassId IN (select id from ApexClass where Name = 'X2c9_CrossAssignmentDeleteBatch')
                                   AND Status NOT IN ('Aborted', 'Completed', 'Failed')
                                   AND JobType = 'BatchApex'];


        if(jobs.isEmpty()) {
            X2c9_CrossAssignmentDeleteBatch batch = new X2c9_CrossAssignmentDeleteBatch();
            batch.timesheetIds = tsIds;
            
            Database.executeBatch(batch, 10);

        } else {
            System.debug('WARN with CrossAssignmentDeleteBatch: There is in-progress batch. jobId=' + jobs.get(0)?.Id);
        }
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('[START] CrossAssignmentDeleteBatch.start');
        updateValidationSetting(true);
        String query = ' SELECT Id, ' +

                       ' (SELECT Id, tc9_et__Timesheet__c FROM tc9_et__Timesheet_Entries__r ' +
                       ' WHERE x2c9_Cross_Assignment_Timesheet_Entry__c = TRUE), ' +

                       ' (SELECT Id, tc9_et__Timesheet__c FROM tc9_et__Pay_Transactions__r ' +
                       ' WHERE tc9_et__Timesheet_Entry__r.x2c9_Cross_Assignment_Timesheet_Entry__c = TRUE ' +
                       ' AND tc9_et__Invoice_Item__c = NULL ' +
                       ' AND tc9_pr__Pay_Batch__c = NULL) ' +

                       ' FROM tc9_et__Timesheet__c ' +
                       ' WHERE tc9_et__Transaction_Creation_Stage__c = \'3\' ' +
                       ' AND x2c9_Cross_Assignment_Status__c = \'Pending Delete\'';

        if (timesheetIds != null && !timesheetIds.isEmpty()) {
            query += ' AND Id IN :timesheetIds';
        }

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<tc9_et__Timesheet__c> timesheets) {
        List<tc9_et__Timesheet_Entry__c> delEntries = new List<tc9_et__Timesheet_Entry__c>();
        List<tc9_pr__Pay_Transaction__c> delPayTrns = new List<tc9_pr__Pay_Transaction__c>();

        for(tc9_et__Timesheet__c ts : timesheets)  {
            if(ts.tc9_et__Timesheet_Entries__r != null) {
                delEntries.addAll(ts.tc9_et__Timesheet_Entries__r);
            }
            if(ts.tc9_et__Pay_Transactions__r != null) {
                delPayTrns.addAll(ts.tc9_et__Pay_Transactions__r);
            }
        }

        Set<Id> failedDelLineTimesheetIdset = new Set<Id>();
        List<tc9_pr__Debug_Log__c> logs = new List<tc9_pr__Debug_Log__c>();

        handleDelete(delPayTrns, 'Pay Transactions', 'tc9_et__Timesheet__c', failedDelLineTimesheetIdset, logs);
        handleDelete(delEntries, 'Timesheet Entries', 'tc9_et__Timesheet__c', failedDelLineTimesheetIdset, logs);

        insertLogs(logs);
        updateStatus(timesheets, failedDelLineTimesheetIdset);
    }

    public void finish(Database.BatchableContext bc) {
        updateValidationSetting(false);
    }

    private static void insertLogs(List<tc9_pr__Debug_Log__c> logs) {
        if(!logs.isEmpty()) {
            tc9_pr__Debug_Header__c header = buildDebugHeader();
            insert header;

            for(tc9_pr__Debug_Log__c log : logs) {
                log.tc9_pr__Debug_Header__c = header.Id;
            }
            insert logs;
        }
    }

    private static void updateStatus(List<tc9_et__Timesheet__c> timesheets, Set<Id> failedDelLineTimesheetIdset) {
        for(tc9_et__Timesheet__c ts : timesheets)  {
            ts.x2c9_Cross_Assignment_Status__c = 'Complete';

            if(failedDelLineTimesheetIdset.contains(ts.Id)) {
                ts.x2c9_Cross_Assignment_Status__c = 'Delete Failed';
                ts.x2c9_Cross_Assignment_Details__c = 'Cross-Assignment Delete Failed, Check Debug Logs for Error - ' + System.now(); 
            }
        }

        update timesheets;
    }

    @SuppressWarnings('PMD.ExcessiveParameterList')
    private static void handleDelete(List<SObject> records, String objectLabel, String parentField, Set<Id> failedTimesheetIds, List<tc9_pr__Debug_Log__c> logs) {
        if (records.isEmpty()) {
            return;
        }

        Database.DeleteResult[] delResults = Database.delete(records, false);
        for (Integer i = 0; i < delResults.size(); i++) {
            if (!delResults[i].isSuccess()) {
                logs.add(buildDebugLog(records[i].Id, objectLabel, JSON.serialize(delResults[i].getErrors())));
                failedTimesheetIds.add((Id) records[i].get(parentField));
            }
        }
    }


    public static tc9_pr__Debug_Header__c buildDebugHeader() {
        tc9_pr__Debug_Header__c header = new tc9_pr__Debug_Header__c();
        header.tc9_pr__Area__c = 'CrossAssignmentDeleteBatch';
        header.tc9_pr__Description__c = 'One or more errors from CrossAssignmentDeleteBatch. See Debug Lines for details.';
        header.tc9_pr__Process_Name__c = 'Delete dummy Cross-Assignment Timesheet Entries and Pay Transactions after Timesheet interpretation';
        
        return header;
    }
    
    public static tc9_pr__Debug_Log__c buildDebugLog( String recordId, String objectName, String error) {
        tc9_pr__Debug_Log__c log = new tc9_pr__Debug_Log__c();
        log.tc9_pr__Area__c = 'CrossAssignmentDeleteBatch';
        log.tc9_pr__Record_Detail__c = '<a href="/' + recordId + '" target="_blank">' + recordId + '</a>';
        log.tc9_pr__Source__c = 'Delete dummy Cross-Assignment ' + objectName + ' after Timesheet interpretation';
        log.tc9_pr__Record_Type__c = recordId;
        log.tc9_pr__Description__c = error?.left(10000);
        
        return log;
    }

    private static void updateValidationSetting(Boolean ovTSE) {
        tc9_pr__Override_TC9P_Validation__c setting = tc9_pr__Override_TC9P_Validation__c.getOrgDefaults();
        setting.tc9_et__OV_Timesheet_Entry__c = ovTSE;
        setting.tc9_et__OV_Timesheet__c = ovTSE;
        update setting;
    }
}